### ISSUE TITLE
Filenotfound exception when I try to open the histogram

### ISSUE THREAD

**Issue by Yagudagu** [MechaTechnica/youtube#1]
Hey, cool sample here, really helpful in learning how to embed python in cs.

The main UI is working, but I'm getting this file not found exception when I try to open the histogram. Just curious if you have any ideas what might have cause it. Thanks!

Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
Exception thrown: 'Python.Runtime.PythonException' in Python.Runtime.dll
The thread 0x498 has exited with code 0 (0x0).
The thread 0x2394 has exited with code 0 (0x0).
The thread 0x7f8 has exited with code 0 (0x0).
The thread 0x2ffc has exited with code 0 (0x0).
The thread 0x271c has exited with code 0 (0x0).
The program '[9272] PythonHospitalDemo.exe' has exited with code 0 (0x0).
The program '[9272] PythonHospitalDemo.exe: Program Trace' has exited with code 0 (0x0).

**Comment by MechaTechnica** [comment]
Is it a hard crash?  Did you install matplotlib and Python3.7?
I will need more info so I added logging. 
See this commit: 
[617e5e6](https://github.com/MechaTechnica/youtube/commit/617e5e6ec251e24be6508cdec082aa6da80975a3)
Try again and let me know if you have issues.

**Comment by MechaTechnica** [comment]
Closing, no response / additional details provided
